# Wallet addresses (PRIVATE â€“ never committed)
ETH_ADDRESS  = "0x7f3eeB908681990e7Cb5f03f343599b8A4161925"
BASE_ADDRESS = "0x7f3eeB908681990e7Cb5f03f343599b8A4161925"
SOL_ADDRESS  = "7zbqKmeCUvKR1mqFHw69NK66W8gK11H6AxCAFYw3RYB7"

# API keys
ALCHEMY_KEY = "vcRwe7ueXeP-BSbh09no1"
HELIUS_KEY  = "1bae1422-b16b-4d51-b717-7fbd3c48540a"

COINBASE_KEY_ID = "6995f655-213b-4f6f-b059-87cb93c845ef"

COINBASE_PRIVATE_KEY = """
-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIAcfUjVvQsww6KtdqkfsPCFdJ991uQGZcbMzi7MnqxRyoAoGCCqGSM49\nAwEHoUQDQgAEtFEvlI52HMUDBHajkGkbz05yuw1MO5toKa/eyzZxtss/z8ebfUdV\nLccaRfxjqqdDYLF+8D8tTdqx3ljHsPkf4g==\n-----END EC PRIVATE KEY-----\n
"""


